apiVersion: v1
kind: Service
metadata:
  name: cluster-seed-netcore21-akka138
  labels:
    app: cluster-seed-netcore21-akka138
spec:
  ports:
  - port: 2552
    protocol: TCP
    targetPort: 2552
  selector:
    cluster: node
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cluster-seed-netcore21-akka138
  labels:
    app: cluster-seed-netcore21-akka138
spec:
  serviceName: cluster-seed-netcore21-akka138
  replicas: 3
  selector:
    matchLabels:
      cluster: node
  template:
    metadata:
      labels:
        cluster: node
    spec:
      containers:
      - name: cluster-seed-netcore21-akka138
        image: cluster-issue-netcore21-akka138:0.0.2
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_SEEDS
          value: akka.tcp://cluster-system@cluster-seed-netcore21-akka138-0.cluster-seed-netcore21-akka138:2552
        command: [ "/bin/sh", "-c", "CLUSTER_IP=${POD_NAME}.cluster-seed-netcore21-akka138 dotnet SimpleCluster_NetCore21_Akka138.dll"]
        livenessProbe:
          tcpSocket:
            port: 2552
        ports:
        - containerPort: 2552
          protocol: TCP